from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional


class SensorReading(BaseModel):
    sensor_id: str
    temperature: float = Field(..., description="Temperature in Celsius")
    humidity: float = Field(..., description="Relative humidity percentage")
    co2_ppm: Optional[float] = Field(None, description="CO2 concentration in ppm")
    co_ppm: float = Field(0.0, description="Carbon monoxide concentration in ppm (MQ7 sensor)")
    camera_occupancy: Optional[int] = Field(
        None,
        description=(
            "Current headcount measured by the sensor node's camera (MediaPipe "
            "line-crossing count). Persisted alongside the CO2-derived "
            "actual_occupancy to validate/calibrate the mass-balance proxy. "
            "Not a model feature; None when the node has no camera."
        ),
    )
    is_simulated: bool = Field(False, description="True when generated by the dev tool, not real hardware")
    timestamp: datetime = Field(default_factory=datetime.utcnow)
